add description about learner
golangtokyo/shoten8 pull request #14
Opened 2020-02-16 12:50 UTC by po3rin

# PRの概要
learnerについて追加

# PDFを確認する
textlintとredpenによるルールチェックをクリアするとPDFが生成され、PRに保存場所が通知されます。

2020-02-16 12:52 UTC, budougumi0617 commented
生成されたPDFを確認してください。
https://411-223696238-gh.circle-artifacts.com/0/golangtokyo-shoten8.pdf

2020-02-16 13:09 UTC, budougumi0617 requested changes

2020-02-16 13:09 UTC, budougumi0617 commented on articles/po3rin.re
> +これでクラスターの動的な設定変更機能が完成しました。さらなる応用として、etcdはv3.4からRaftに4つ目のロールである@<b>{learner（学習者）}@<fn>{learner}を実装しています。これはノードの新規追加時にリーダーのログに追いつくまで非投票メンバーとしてクラスターに参加させるというアイデアです。この方法はログ複製でリーダーが過負荷になるのを防ぎ、クラスター再構成の安全性
今までロールみたいな話出てましたっけ？「ロール」とか「役割」でgrepしてみたのですが、ありませんでした。リーダーとかフォロワーがロールですか？（それにしても3つ目がなかったような）
1,2,3の説明がないところで、いきなり4つ目といわれると「？？？」ってなりました。

2020-02-16 13:09 UTC, budougumi0617 commented on articles/po3rin.re
> +これでクラスターの動的な設定変更機能が完成しました。さらなる応用として、etcdはv3.4からRaftに4つ目のロールである@<b>{learner（学習者）}@<fn>{learner}を実装しています。これはノードの新規追加時にリーダーのログに追いつくまで非投票メンバーとしてクラスターに参加させるというアイデアです。この方法はログ複製でリーダーが過負荷になるのを防ぎ、クラスター再構成の安全性
```
4つ目のロールである@<b>{learner（学習者）}@<fn>{learner}を実装しています。
詳しくはetcdのドキュメントをご覧ください@<fn>{learner}
```

参照が同じですけどダイジョブですか？
learner の説明がetcdのドキュメントということは、learnerとはRaftの論文には出てこないetcdが勝手に追加したロールってことですかね？？？

2020-02-16 14:24 UTC, po3rin commented on articles/po3rin.re
> +これでクラスターの動的な設定変更機能が完成しました。さらなる応用として、etcdはv3.4からRaftに4つ目のロールである@<b>{learner（学習者）}@<fn>{learner}を実装しています。これはノードの新規追加時にリーダーのログに追いつくまで非投票メンバーとしてクラスターに参加させるというアイデアです。この方法はログ複製でリーダーが過負荷になるのを防ぎ、クラスター再構成の安全性
3つめは「候補者」ですね。太字にしときます。
わかりやすいようにここではリーダー、フォロワー、候補者と並列で並べておきます。

2020-02-16 14:27 UTC, po3rin commented on articles/po3rin.re
> +これでクラスターの動的な設定変更機能が完成しました。さらなる応用として、etcdはv3.4からRaftに4つ目のロールである@<b>{learner（学習者）}@<fn>{learner}を実装しています。これはノードの新規追加時にリーダーのログに追いつくまで非投票メンバーとしてクラスターに参加させるというアイデアです。この方法はログ複製でリーダーが過負荷になるのを防ぎ、クラスター再構成の安全性
いえ、learnerの良い説明がetcdにあるからですね。これ以上だと論文になるので、ここではlearnerを理解できる最もシンプルなものを引用していますがいかがでしょうか

2020-02-16 14:35 UTC, budougumi0617 commented
生成されたPDFを確認してください。
https://416-223696238-gh.circle-artifacts.com/0/golangtokyo-shoten8.pdf

2020-02-16 20:50 UTC, budougumi0617 commented on articles/po3rin.re
> +これでクラスターの動的な設定変更機能が完成しました。さらなる応用として、etcdはv3.4からRaftに4つ目のロールである@<b>{learner（学習者）}@<fn>{learner}を実装しています。これはノードの新規追加時にリーダーのログに追いつくまで非投票メンバーとしてクラスターに参加させるというアイデアです。この方法はログ複製でリーダーが過負荷になるのを防ぎ、クラスター再構成の安全性
なるほど！定義の参照はわかりやすさより1次ソースを優先したほうがいいと思いますね。
（`わかりやすいのはetcdのほうです。`みたいに2つ引用してもいいかと思います）
Re:VIEWのバグなのかおなじ内容なのに2回でているのも気になり
<img width="518" alt="スクリーンショット 2020-02-17 5 46 57" src="https://user-images.githubusercontent.com/1883265/74612531-75db7300-5149-11ea-8e6e-8c3ef8075b82.png">

2020-02-16 20:55 UTC, budougumi0617 commented on articles/po3rin.re
> +これでクラスターの動的な設定変更機能が完成しました。さらなる応用として、etcdはv3.4からRaftに「リーダー、フォロワー、候補者」に次ぐ4つ目のロールである@<b>{learner（学習者）}@<fn>{learner}を実装しています。これはノードの新規追加時にリーダーのログに追いつくまで非投票メンバーとしてクラスターに参加させるというアイデアです。この方法はログ複製でリーダーが過負荷に
あー、そっか、上の文だと`各メンバーはリーダー、フォロワー、候補者のいずれかの状態`みたいに「状態」扱いなのに、ここだと`「リーダー、フォロワー、候補者」に次ぐ4つ目のロール`と「ロール」扱いだから探せなかったのだと気づきました。
どちらが「ロール」と「状態」、正しい用語はどちらですかね？（`status`と`role`は違う概念だと思うんですが…）

2020-02-16 23:50 UTC, po3rin commented on articles/po3rin.re
> +これでクラスターの動的な設定変更機能が完成しました。さらなる応用として、etcdはv3.4からRaftに「リーダー、フォロワー、候補者」に次ぐ4つ目のロールである@<b>{learner（学習者）}@<fn>{learner}を実装しています。これはノードの新規追加時にリーダーのログに追いつくまで非投票メンバーとしてクラスターに参加させるというアイデアです。この方法はログ複製でリーダーが過負荷に
論文に合わせてstates = 状態 にします

2020-02-17 00:10 UTC, po3rin commented on articles/po3rin.re
> +これでクラスターの動的な設定変更機能が完成しました。さらなる応用として、etcdはv3.4からRaftに4つ目のロールである@<b>{learner（学習者）}@<fn>{learner}を実装しています。これはノードの新規追加時にリーダーのログに追いつくまで非投票メンバーとしてクラスターに参加させるというアイデアです。この方法はログ複製でリーダーが過負荷になるのを防ぎ、クラスター再構成の安全性
learnerの概念はRaftの実践を考察した[論文](https://github.com/ongardie/dissertation/blob/master/stanford.pdf)で紹介されているのですが「learner」という単語が無くnon-vorting member（非投票者）として導入されているので、一次ソースを出した上で、etcdにおけるlearnerのデザインについてのドキュメントを引用する形ではどうでしょうか。これで引用が重複することもなくなります。

```
さらなる応用として、etcdはv3.4からRaftに「リーダー、フォロワー、候補者」に次ぐ4つ目の状態である@<b>{learner（学習者）}@<fn>{learner}を実装しています(コンセンサスアルゴリズムの実践を考察した論文@<fn>{raft-plactice}では@<b>{non-vorting member（非投票者）}として導入されている)。
```

2020-02-17 00:16 UTC, po3rin commented on articles/po3rin.re
> +これでクラスターの動的な設定変更機能が完成しました。さらなる応用として、etcdはv3.4からRaftに4つ目のロールである@<b>{learner（学習者）}@<fn>{learner}を実装しています。これはノードの新規追加時にリーダーのログに追いつくまで非投票メンバーとしてクラスターに参加させるというアイデアです。この方法はログ複製でリーダーが過負荷になるのを防ぎ、クラスター再構成の安全性
こちらの一次ソースと思われるこちらの[論文](https://github.com/ongardie/dissertation/blob/master/stanford.pdf)ではlearnerの概念は出てきますがlearnerという言葉ではなく「non-vorting member（非投票者）」として導入されているので、一次ソースとして論文を引用しつつetcdのデザインとしてのlearnerはetcdのデザインドキュメントを引用しようと思いますがいかがでしょうか。

2020-02-17 00:18 UTC, budougumi0617 commented on articles/po3rin.re
> +これでクラスターの動的な設定変更機能が完成しました。さらなる応用として、etcdはv3.4からRaftに「リーダー、フォロワー、候補者」に次ぐ4つ目の状態である@<b>{learner（学習者）}@<fn>{learner}を実装しています(コンセンサスアルゴリズムの実践を考察した論文@<fn>{raft-plactice}では@<b>{non-vorting member（非投票者）}として導
**[RedPen]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
ValidationError[WordNumber], 一文に存在する単語数 (70) が最大値 "50" を超えています．。 at line: さらなる応用として、etcdはv3.4からRaftに「リーダー、フォロワー、候補者」に次ぐ4つ目の状態であるlearner（学習者）learnerを実装しています(コンセンサスアルゴリズムの実践を考察した論文raft-placticeではnon-vorting member（非投票者）として導入されている)。

2020-02-17 00:18 UTC, budougumi0617 commented on articles/po3rin.re
> +これでクラスターの動的な設定変更機能が完成しました。さらなる応用として、etcdはv3.4からRaftに「リーダー、フォロワー、候補者」に次ぐ4つ目の状態である@<b>{learner（学習者）}@<fn>{learner}を実装しています(コンセンサスアルゴリズムの実践を考察した論文@<fn>{raft-plactice}では@<b>{non-vorting member（非投票者）}として導
**[RedPen]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
ValidationError[ParenthesizedSentence], 括弧のネストが深すぎます。 at line: さらなる応用として、etcdはv3.4からRaftに「リーダー、フォロワー、候補者」に次ぐ4つ目の状態であるlearner（学習者）learnerを実装しています(コンセンサスアルゴリズムの実践を考察した論文raft-placticeではnon-vorting member（非投票者）として導入されている)。

2020-02-17 00:19 UTC, budougumi0617 commented on articles/po3rin.re
> +これでクラスターの動的な設定変更機能が完成しました。さらなる応用として、etcdはv3.4からRaftに「リーダー、フォロワー、候補者」に次ぐ4つ目の状態である@<b>{learner（学習者）}@<fn>{learner}を実装しています(コンセンサスアルゴリズムの実践を考察した論文@<fn>{raft-plactice}では@<b>{non-vorting member（非投票者）}として導
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
Line 1252 sentence length(135) exceeds the maximum sentence length of 100.
Over 35 characters. (ja-technical-writing/sentence-length)

2020-02-17 00:19 UTC, budougumi0617 commented on articles/po3rin.re
> +これでクラスターの動的な設定変更機能が完成しました。さらなる応用として、etcdはv3.4からRaftに「リーダー、フォロワー、候補者」に次ぐ4つ目の状態である@<b>{learner（学習者）}@<fn>{learner}を実装しています(コンセンサスアルゴリズムの実践を考察した論文@<fn>{raft-plactice}では@<b>{non-vorting member（非投票者）}として導
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
の無い => のなの (prh)

2020-02-17 00:19 UTC, budougumi0617 commented on articles/po3rin.re
> +これでクラスターの動的な設定変更機能が完成しました。さらなる応用として、etcdはv3.4からRaftに「リーダー、フォロワー、候補者」に次ぐ4つ目の状態である@<b>{learner（学習者）}@<fn>{learner}を実装しています(コンセンサスアルゴリズムの実践を考察した論文@<fn>{raft-plactice}では@<b>{non-vorting member（非投票者）}として導
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
なの => ない (prh)

2020-02-17 00:20 UTC, po3rin commented
あーlintかけ忘れた。。

2020-02-17 00:25 UTC, budougumi0617 commented
生成されたPDFを確認してください。
https://476-223696238-gh.circle-artifacts.com/0/golangtokyo-shoten8.pdf

2020-02-17 01:48 UTC, budougumi0617 approved these changes
LGTM

2020-02-17 01:48 UTC, merged