[WIP] GoとコンセンサスアルゴリズムRaftによる分散システム構築入門
golangtokyo/shoten8 pull request #7
Opened 2020-02-02 14:54 UTC by po3rin

意味がわかるか & Goのコードでもっとこう書いた方がよいというのを指摘いただきたいです。。

## TODO

- [ ] サンプルコードの準備
- [ ] スナップショットの実装(時間あれば)

2020-02-02 22:05 UTC, budougumi0617 commented on articles/po3rin.re
> += GoとコンセンサスアルゴリズムRaftによる分散システム構築入門
**[RedPen]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
ValidationError[VoidSection], 節の内容が空です。 at line: GoとコンセンサスアルゴリズムRaftによる分散システム構築入門

2020-02-02 22:05 UTC, budougumi0617 commented on articles/po3rin.re
> +=== Raftで分散キーバリューストアを実装する
**[RedPen]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
ValidationError[ParagraphNumber], セクション内のパラグラフ数が最大の"10"を超えています at line: Raftで分散キーバリューストアを実装する

2020-02-02 22:05 UTC, budougumi0617 commented on articles/po3rin.re
> +=== Raftで分散キーバリューストアを実装する
**[RedPen]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
ValidationError[SectionLength], セクション内の文字数が最大の"1,500"を超えています（5,251） at line: Raftで分散キーバリューストアを実装する

2020-02-02 22:05 UTC, budougumi0617 commented on articles/po3rin.re
> +=== クラスターの動的な構成変更
**[RedPen]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
ValidationError[ParagraphNumber], セクション内のパラグラフ数が最大の"10"を超えています at line: クラスターの動的な構成変更

2020-02-02 22:05 UTC, budougumi0617 commented on articles/po3rin.re
> +これで、いつデータストアがダウンしてもログを順番に適用すれば元の状態に戻せます。先ほど説明したように「同じ操作を同じ順序で実行すれば必ず同じ状態になる」ことが分かっているからです。ここで「一部のログが欠落したらどうするのか」「ログの順序が入れ替わったらどうるるのか」という疑問が生まれているはずです。複製されたログの一貫性を保つことがコンセンサスアルゴリズムの仕事です。次の節からはコンセンサスアル
**[RedPen]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
ValidationError[Okurigana], 不正な送り仮名 "落し" がみつかりました。 at line: ここで「一部のログが欠落したらどうするのか」「ログの順序が入れ替わったらどうるるのか」という疑問が生まれているはずです。

2020-02-02 22:05 UTC, budougumi0617 commented on articles/po3rin.re
> +使ってオリジナルの分散〇〇を作ってみてください。
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
"〇" が連続して2回使われています。 (ja-technical-writing/ja-no-successive-word)

2020-02-03 11:04 UTC, budougumi0617 commented on articles/po3rin.re
> +== クラスターの動的な構成変更
**[RedPen]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
ValidationError[ParagraphNumber], セクション内のパラグラフ数が最大の"10"を超えています at line: クラスターの動的な構成変更

2020-02-04 06:57 UTC, budougumi0617 commented
生成されたPDFを確認してください。
https://168-223696238-gh.circle-artifacts.com/0/golangtokyo-shoten8.pdf

2020-02-04 07:01 UTC, budougumi0617 commented
生成されたPDFを確認してください。
https://173-223696238-gh.circle-artifacts.com/0/golangtokyo-shoten8.pdf

2020-02-06 15:36 UTC, budougumi0617 commented
生成されたPDFを確認してください。
https://184-223696238-gh.circle-artifacts.com/0/golangtokyo-shoten8.pdf

2020-02-08 08:53 UTC, budougumi0617 requested changes
ひとまず途中まで。

2020-02-08 08:53 UTC, budougumi0617 commented on articles/po3rin.re
> +こんにちは@po3rin@<fn>{po3rin}です。仕事ではメインでGoを使っています。今回は@<b>{コンセンサスアルゴリズム}の1つである@<b>{Raft}@<fn>{raft}の紹介と、実際にGoとRaftパッケージを使った分散システムの開発の方法を紹介します。Kubernetesの内部でも使われているetcdや、全文検索エンジンのAlgoria、分散データベースのCockroach
> 本性はコンセンサスアルゴリズム初心者向けであり

本章

2020-02-08 08:53 UTC, budougumi0617 commented on articles/po3rin.re
> +@<b>{コンセンサスアルゴリズム}は一貫したグループとして動作し、そのメンバーの一部の障害に耐えることを可能にするアルゴリズムです。安全な分散システムを構築する上で重要な役割を果たします。Raftの前にそもそもなぜコンセンサスアルゴリズムが必要なのかを見ていきましょう。たとえばチームで１つのプロセスだけでデータストアを運用している場合、そのデータストアが障害で落ちたら重大な問題になります。その
目的語（？）が無い気がします。「何が」一貫したグループとして動作するんでしょうか。グループの定義があればいいのかな。メンバーもすごくぼやーっとしていると思いました。

メンバーの一部が障害を発生するということは、なんらかのロールにひもづいたサーバなりプロセスの集団をここではグループ、そしてその構成物「メンバー」と読んでいるんですかね？

2020-02-08 08:53 UTC, budougumi0617 commented on articles/po3rin.re
> +コンセンサスアルゴリズムにはいくつか種類があり、その中で@<b>{Paxos}というアルゴリズムが過去10年間メインで使われ続けていました。一方でPaxosのアルゴリズムはかなり複雑で理解が難しいものでした。そこで登場したのが@<b>{Raft}というアルゴリズムです。Raftの論文によれば、RaftはPaxosと同じくらい信頼性と効率性がある一方で、PaxosよりRaftの方がシンプルで理解し
論文へのリファレンスがほしい気もします。最初のPDF？

2020-02-08 08:53 UTC, budougumi0617 commented on articles/po3rin.re
> +これで、いつデータストアがダウンしてもログを順番に適用すれば元の状態に戻せます。先ほど説明したように「同じ操作を同じ順序で実行すれば必ず同じ状態になる」ことが分かっているからです。ここで「一部のログが欠損したらどうするのか」「ログの順序が入れ替わったらどうするのか」という疑問が生まれているはずです。この複製されたログの一貫性を保つことがコンセンサスアルゴリズムの仕事です。次の節からはコンセンサス
[感想]
データ指向アプリケーションデザインでもこの辺の話が出てきた気がする…

2020-02-08 08:53 UTC, budougumi0617 commented on articles/po3rin.re
> +これで、いつデータストアがダウンしてもログを順番に適用すれば元の状態に戻せます。先ほど説明したように「同じ操作を同じ順序で実行すれば必ず同じ状態になる」ことが分かっているからです。ここで「一部のログが欠損したらどうするのか」「ログの順序が入れ替わったらどうするのか」という疑問が生まれているはずです。この複製されたログの一貫性を保つことがコンセンサスアルゴリズムの仕事です。次の節からはコンセンサス
マスター死んだときに予備のデータストアが昇格するとややこしくなりそうですが、そのへんはあえて触れてないって感じなんですかね？

2020-02-08 08:53 UTC, budougumi0617 commented on articles/po3rin.re
> +これで、いつデータストアがダウンしてもログを順番に適用すれば元の状態に戻せます。先ほど説明したように「同じ操作を同じ順序で実行すれば必ず同じ状態になる」ことが分かっているからです。ここで「一部のログが欠損したらどうするのか」「ログの順序が入れ替わったらどうするのか」という疑問が生まれているはずです。この複製されたログの一貫性を保つことがコンセンサスアルゴリズムの仕事です。次の節からはコンセンサス
マスターじゃなくてリーダーっていうのか。あとのほう読めばわかるのか。

2020-02-08 08:53 UTC, budougumi0617 commented on articles/po3rin.re
> +	s.mu.RLock()
[MUST]
WriteするならRLockじゃだめですよね。

2020-02-08 08:53 UTC, budougumi0617 commented on articles/po3rin.re
> +@<list>{server1}ではhandler型の内部でStoreインターフェースを保持します。これでStoreの実装を切り替えやすくなり、モックテストも行いやすくなります。続いてメソッドを定義します(@<list>{server2})。今回は簡略化のためにフレームワークであるGin@<fn>{gin}を使います。
[IMO]
`handler` とか `Store`らへんもコードのキーワードなので、 `code`とかで装飾したほうがいい気がします。

2020-02-08 08:53 UTC, budougumi0617 commented on articles/po3rin.re
> +		c.JSON(404, gin.H{
[IMO] 
わたしは http.StatusXXX 派かなあ
https://golang.org/pkg/net/http/#pkg-constants

2020-02-08 08:53 UTC, budougumi0617 commented on articles/po3rin.re
> +
ここまで読みました。

2020-02-09 10:08 UTC, po3rin commented on articles/po3rin.re
> +	s.mu.RLock()
おっと！！完全にミスしてますね。失礼しました！

2020-02-09 10:25 UTC, po3rin commented on articles/po3rin.re
> +@<b>{コンセンサスアルゴリズム}は一貫したグループとして動作し、そのメンバーの一部の障害に耐えることを可能にするアルゴリズムです。安全な分散システムを構築する上で重要な役割を果たします。Raftの前にそもそもなぜコンセンサスアルゴリズムが必要なのかを見ていきましょう。たとえばチームで１つのプロセスだけでデータストアを運用している場合、そのデータストアが障害で落ちたら重大な問題になります。その
そうですね。何かしらのグループという意味でも論文で言及されているので、説明難しいですね。。

2020-02-09 10:27 UTC, po3rin commented on articles/po3rin.re
> +コンセンサスアルゴリズムにはいくつか種類があり、その中で@<b>{Paxos}というアルゴリズムが過去10年間メインで使われ続けていました。一方でPaxosのアルゴリズムはかなり複雑で理解が難しいものでした。そこで登場したのが@<b>{Raft}というアルゴリズムです。Raftの論文によれば、RaftはPaxosと同じくらい信頼性と効率性がある一方で、PaxosよりRaftの方がシンプルで理解し
リファレンスを改めてつけておきます

2020-02-09 11:24 UTC, po3rin commented on articles/po3rin.re
> +	s.mu.RLock()
すいません。凡ミスです。

2020-02-09 12:18 UTC, po3rin commented on articles/po3rin.re
> +		c.JSON(404, gin.H{
そうですね！修正します！

2020-02-09 12:24 UTC, po3rin commented on articles/po3rin.re
> +
ありがとうございます！！

2020-02-09 12:25 UTC, po3rin commented on articles/po3rin.re
> +@<list>{server1}ではhandler型の内部でStoreインターフェースを保持します。これでStoreの実装を切り替えやすくなり、モックテストも行いやすくなります。続いてメソッドを定義します(@<list>{server2})。今回は簡略化のためにフレームワークであるGin@<fn>{gin}を使います。
そうですね。つけておきます！

2020-02-09 12:47 UTC, budougumi0617 commented on articles/po3rin.re
> +@<list>{server.run}ではAPIの起動に必要な@<code>{Server}の初期化を@<code>{New}関数で行い、@<code>{Server.Run}メソッドで実際の立ち上げを行います。@<code>{Server.Run}では引数にcontext.Contextを受けて、コンテキストがキャンセルされたら@<code>{ListenAndServe}を止められるようにし
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
止め => やめ (prh)

2020-02-09 12:47 UTC, budougumi0617 commented on articles/po3rin.re
> +@<list>{server.run}ではAPIの起動に必要な@<code>{Server}の初期化を@<code>{New}関数で行い、@<code>{Server.Run}メソッドで実際の立ち上げを行います。@<code>{Server.Run}では引数にcontext.Contextを受けて、コンテキストがキャンセルされたら@<code>{ListenAndServe}を止められるようにし
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
することができ => でき (prh)

2020-02-09 12:47 UTC, budougumi0617 commented on articles/po3rin.re
> +@<list>{server.run}ではAPIの起動に必要な@<code>{Server}の初期化を@<code>{New}関数で行い、@<code>{Server.Run}メソッドで実際の立ち上げを行います。@<code>{Server.Run}では引数にcontext.Contextを受けて、コンテキストがキャンセルされたら@<code>{ListenAndServe}を止められるようにし
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
"することができます"は冗長な表現です。"することが"を省き簡潔な表現にすると文章が明瞭になります。参考: http://qiita.com/takahi-i/items/a93dc2ff42af6b93f6e0 (ja-technical-writing/ja-no-redundant-expression)

2020-02-09 12:47 UTC, budougumi0617 commented on articles/po3rin.re
> +@<list>{server.run}ではAPIの起動に必要な@<code>{Server}の初期化を@<code>{New}関数で行い、@<code>{Server.Run}メソッドで実際の立ち上げを行います。@<code>{Server.Run}では引数にcontext.Contextを受けて、コンテキストがキャンセルされたら@<code>{ListenAndServe}を止められるようにし
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
返り値 => 戻り値 (prh)

2020-02-09 12:53 UTC, budougumi0617 commented
生成されたPDFを確認してください。
https://213-223696238-gh.circle-artifacts.com/0/golangtokyo-shoten8.pdf

2020-02-09 12:55 UTC, po3rin commented on articles/po3rin.re
> +これで、いつデータストアがダウンしてもログを順番に適用すれば元の状態に戻せます。先ほど説明したように「同じ操作を同じ順序で実行すれば必ず同じ状態になる」ことが分かっているからです。ここで「一部のログが欠損したらどうするのか」「ログの順序が入れ替わったらどうするのか」という疑問が生まれているはずです。この複製されたログの一貫性を保つことがコンセンサスアルゴリズムの仕事です。次の節からはコンセンサス
Raftのコンテキストではリーダーですね

2020-02-09 12:56 UTC, po3rin commented on articles/po3rin.re
> +@<b>{コンセンサスアルゴリズム}は一貫したグループとして動作し、そのメンバーの一部の障害に耐えることを可能にするアルゴリズムです。安全な分散システムを構築する上で重要な役割を果たします。Raftの前にそもそもなぜコンセンサスアルゴリズムが必要なのかを見ていきましょう。たとえばチームで１つのプロセスだけでデータストアを運用している場合、そのデータストアが障害で落ちたら重大な問題になります。その
少し馴染みのある言葉に変えました。

2020-02-09 12:59 UTC, po3rin commented
少し、ノードの終了時の片付けコードを修正します！レビューいただける方は少々お待ちください。。

2020-02-09 14:51 UTC, budougumi0617 commented
生成されたPDFを確認してください。
https://223-223696238-gh.circle-artifacts.com/0/golangtokyo-shoten8.pdf

2020-02-10 11:15 UTC, budougumi0617 commented
生成されたPDFを確認してください。
https://235-223696238-gh.circle-artifacts.com/0/golangtokyo-shoten8.pdf

2020-02-10 12:11 UTC, po3rin commented
コード修正しました。長くなってすいません。。

2020-02-10 12:14 UTC, budougumi0617 commented
生成されたPDFを確認してください。
https://240-223696238-gh.circle-artifacts.com/0/golangtokyo-shoten8.pdf

2020-02-11 21:46 UTC, budougumi0617 commented on articles/po3rin.re
> +@<img>{arch}をみて分かるとおりRaftで別のノードと通信する必要があるのでそれらの管理もこのraftalgパッケージの責務です。etcd/raftが本当にRaftアルゴリズムのコアだけに集中して作られたパッケージだということが見て取れます。このraftalgパッケージを使うと先ほどの実装(@<img>{kv})が@<img>{arch2}のように変わります。
> 先ほどの実装(@<img>{kv})が@<img>{arch2}のように変わります。

比較画像ならば同じ条件でみたい気がするんですけど、`arch2` からはGETが消えている気がします。
（性格が悪いので、もしかしてGET書くとそんなにシンプルな図にはならない？と邪推してしまう）
<img width="833" alt="スクリーンショット 2020-02-12 6 43 51" src="https://user-images.githubusercontent.com/1883265/74282320-46042800-4d63-11ea-8b57-5384e14c4f5f.png">
<img width="938" alt="スクリーンショット 2020-02-12 6 44 04" src="https://user-images.githubusercontent.com/1883265/74282332-4d2b3600-4d63-11ea-9f1e-c277b70d95b6.png">

2020-02-11 21:47 UTC, budougumi0617 commented on articles/po3rin.re
> +この節では最終的に@<list>{tree2}ような構成になります。
`の`ような

2020-02-11 21:50 UTC, budougumi0617 commented on articles/po3rin.re
> +//}
微妙にはみ出ているけれどこれはどうしようもない気もする…（申し送り書いて2行で書くとか。。。？
<img width="891" alt="スクリーンショット 2020-02-12 6 49 21" src="https://user-images.githubusercontent.com/1883265/74282654-de9aa800-4d63-11ea-979e-b05c79842248.png">

2020-02-11 21:51 UTC, budougumi0617 commented on articles/po3rin.re
> +そしてクラスターのメンバーのURLをetcd/raftパッケージで使う用の型に変換します。最終的にノードを起動するための関数の引数に渡すためです@<list>{peers}。
`関数の引数に渡すためですリスト3.14` になってますね

2020-02-11 22:04 UTC, budougumi0617 commented on articles/po3rin.re
> +	}
smart!

2020-02-11 22:15 UTC, budougumi0617 commented on articles/po3rin.re
> +		// 適用して良いをエントリをチャネル経由で通知
片言になってますね

2020-02-11 22:26 UTC, budougumi0617 commented on articles/po3rin.re
> +	<-ctx.Done()
あとみてないですけど、この段階のコードならば `<-ctx.Done()` で止まってますし、

```go
if err := srv.ListenAndServe(); err != nil{
  return err
}
```

でいいのでは？

2020-02-11 22:29 UTC, budougumi0617 commented on articles/po3rin.re
> +	if err := srv.Shutdown(sCtx); err != nil {
私もあまり確証無いんですけど、`ListenAndServe` が戻り値帰ってきたとき、Shutdownする必要あるんでしたっけ？（もう終了処理終わってそう）

（かりにShutdownを呼ぶ意味があるとしても、）contextで1秒で強制的に終わるならば、どのみち呼んで安全に終わらせていないような。

2020-02-11 22:32 UTC, budougumi0617 commented on articles/po3rin.re
> +	<-ctx.Done()
あー、なるほど、`serveRaftHTTP`の呼び出し元でキャンセルされることを想定しているのか、なるほど理解 🙇

2020-02-11 22:33 UTC, budougumi0617 commented on articles/po3rin.re
> +	if err := srv.Shutdown(sCtx); err != nil {
こっちも`ListenAndServe`が終わらない状態でシャットダウンされるタイミングがあることを理解しました。
（ただグレースフルシャットダウンしていないのはちょっと気になる）

2020-02-11 22:36 UTC, budougumi0617 commented on articles/po3rin.re
> +=== Raftや外部パッケージとのやりとりをチャネルでさばく
ここまで読みましたマーク

2020-02-11 22:37 UTC, budougumi0617 commented on articles/po3rin.re
> +=== Raftや外部パッケージとのやりとりをチャネルでさばく
まだ半分くらいだったｗｗ

2020-02-12 05:16 UTC, budougumi0617 requested changes
やっと一通り読めました。大作！！

2020-02-12 05:16 UTC, budougumi0617 commented on articles/po3rin.re
> +ここではコンテキストキャンセルや、トランスポーターからのエラーを受ける以外に、重要な２つのcaseを扱っています。１つ目のcaseは定期的に@<code>{time.Ticker}で実行しなければならない@<code>{raft.Node.Tick}メソッドを実行するケースです。Raftには、ハートビートと選挙タイムアウトの2つの重要なタイムアウトがあると説明しました。etcd/raftパッケー
caseはGoの予約語なので装飾したほうがよさそう。

2020-02-12 05:16 UTC, budougumi0617 commented on articles/po3rin.re
> +ここではコンテキストキャンセルや、トランスポーターからのエラーを受ける以外に、重要な２つのcaseを扱っています。１つ目のcaseは定期的に@<code>{time.Ticker}で実行しなければならない@<code>{raft.Node.Tick}メソッドを実行するケースです。Raftには、ハートビートと選挙タイムアウトの2つの重要なタイムアウトがあると説明しました。etcd/raftパッケー
`State Mashine` 

Machine

2020-02-12 05:16 UTC, budougumi0617 commented on articles/po3rin.re
> +//}
> function wrap channelパターン

[IMO]
ラップしているのはファンクションじゃなくて構造体かなと思いました。（ファンクションじゃなくてメソッドでは、というキモチも少しある）

2020-02-12 05:16 UTC, budougumi0617 commented on articles/po3rin.re
> +raftalgパッケージの最後にstoreパッケージがRaftを利用できるようにメソッドを準備してあげます。Proposeが内部でログのコンセンサスをとってくれます。
ここもProposeはメソッド名なので装飾したほうがよさそう。

2020-02-12 05:16 UTC, budougumi0617 commented on articles/po3rin.re
> +	err := gob.NewEncoder(&buf).Encode(kv{key, value});
なぞのセミコロン

2020-02-12 05:16 UTC, budougumi0617 commented on articles/po3rin.re
> +ここまでの実装で気付きでしょうが、@<list>{main3}においてgorutineで走らせているすべての関数はcontextでキャンセル可能になっています。これにより特定のシグナルもしくはerrgroupがエラーを検知したらコンテキストキャンセルが行われ、すべてのgorutineで起動しているプロセスをきっちり終了できます(@<img>{cancel})。当然@<code>{SIGTERM}
https://github.com/golangtokyo/shoten8/pull/7/files#r377940047

上で書いたとおり、サーバのリクエスト処理の終了を待っていないので、「きっちり終了」しているかと言われるとちょっと疑問が残ります。スレッド的には全部ちゃんと死にそうですが…

2020-02-12 05:16 UTC, budougumi0617 commented on articles/po3rin.re
> +ここまでの実装で気付きでしょうが、@<list>{main3}においてgorutineで走らせているすべての関数はcontextでキャンセル可能になっています。これにより特定のシグナルもしくはerrgroupがエラーを検知したらコンテキストキャンセルが行われ、すべてのgorutineで起動しているプロセスをきっちり終了できます(@<img>{cancel})。当然@<code>{SIGTERM}
> gorutineで起動しているプロセスをきっちり終了できます

[MUST]
goroutineで増えるのはスレッドであってプロセスじゃないですよね？
（厳密に言うとスレッドって書くのもちょっと微妙ですが）

2020-02-12 05:16 UTC, budougumi0617 commented on articles/po3rin.re
> +立ち上げた時点では、リーダー選挙のようすがログで見れます。その中でkvraft2のログの重要部分だけを抽出してみます(@<list>{log})。
様子？

2020-02-12 05:16 UTC, budougumi0617 commented on articles/po3rin.re
> +今までの実装ではクラスターのノードを起動時に固定しなければなりません。たとえば、運用中にノード数を3から5にしたい時は、またクラスターごと再起動しなければいけません。これでは困るので動的にクラスターのノード数を変更できるようにしてあげましょう。ここからのコードの変更は@<code>{https://github.com/po3rin/kvraft/commit/****}に差分が置いてあります。
https://github.com/po3rin/kvraft

なさそう。リポジトリネームが変わっている？

2020-02-12 05:16 UTC, budougumi0617 commented on articles/po3rin.re
> +@<list>{ChangeConf}ではとりあえずノードの追加と削除をサポートしました。この関数をAPIからstoreパッケージ経由でコールできるようにすれば良さそうです。@<code>{raft.RaftNode.ProposeConfChange}の結果はチャネル経由で@<code>{[]raftpb.Entry}型として受け取れます。そのため@<code>{[]raftpb.Entry}
> あげます@<list>{publishEntries}。

ここもちょっと変ですね。

2020-02-12 05:16 UTC, budougumi0617 commented on articles/po3rin.re
> +		// 先ほどの実装そのまま
先ほどだとどこのことなのか難しいですね…

2020-02-12 05:16 UTC, budougumi0617 commented on articles/po3rin.re
> +これでraftalgパッケージの修正が終わりました。続いてstoreパッケージを修正します。具体的には@<code>{*RaftAlg.ChangeConf}をcallするようにします@<list>{store5}。
> します@<list>{store5}。

2020-02-12 05:16 UTC, budougumi0617 commented on articles/po3rin.re
> +続いてAPIでクラスタの設定を変更するエンドポイントを追加してあげます@<list>{server3}。
ここも。`あげますリスト...`になっている

2020-02-12 09:17 UTC, po3rin commented on articles/po3rin.re
> +@<img>{arch}をみて分かるとおりRaftで別のノードと通信する必要があるのでそれらの管理もこのraftalgパッケージの責務です。etcd/raftが本当にRaftアルゴリズムのコアだけに集中して作られたパッケージだということが見て取れます。このraftalgパッケージを使うと先ほどの実装(@<img>{kv})が@<img>{arch2}のように変わります。
なるほど。。ではGETも図示します

2020-02-12 09:18 UTC, po3rin commented on articles/po3rin.re
> +	<-ctx.Done()
これは実装時に説明したほうが良さそうですね

2020-02-12 09:52 UTC, po3rin commented on articles/po3rin.re
> +今までの実装ではクラスターのノードを起動時に固定しなければなりません。たとえば、運用中にノード数を3から5にしたい時は、またクラスターごと再起動しなければいけません。これでは困るので動的にクラスターのノード数を変更できるようにしてあげましょう。ここからのコードの変更は@<code>{https://github.com/po3rin/kvraft/commit/****}に差分が置いてあります。
あ、まだコードが変わる恐れがあるので準備していないです。

2020-02-12 09:53 UTC, po3rin commented on articles/po3rin.re
> +		// 先ほどの実装そのまま
確かに、、紛らわしいので消します

2020-02-12 09:58 UTC, po3rin commented on articles/po3rin.re
> +//}
そうですね！ありがとうございます！

2020-02-12 10:04 UTC, budougumi0617 commented
生成されたPDFを確認してください。
https://270-223696238-gh.circle-artifacts.com/0/golangtokyo-shoten8.pdf

2020-02-12 10:06 UTC, po3rin commented on articles/po3rin.re
> +	if err := srv.Shutdown(sCtx); err != nil {
そうですね。グレースフルシャットダウンのくせにタイムアウトを短くしすぎているので、リクエスト処理の終了をしっかり待つ意味で30秒とかにします。

2020-02-12 10:06 UTC, po3rin commented on articles/po3rin.re
> +ここまでの実装で気付きでしょうが、@<list>{main3}においてgorutineで走らせているすべての関数はcontextでキャンセル可能になっています。これにより特定のシグナルもしくはerrgroupがエラーを検知したらコンテキストキャンセルが行われ、すべてのgorutineで起動しているプロセスをきっちり終了できます(@<img>{cancel})。当然@<code>{SIGTERM}
https://github.com/golangtokyo/shoten8/pull/7/files#discussion_r377938400
で返信しています。

2020-02-12 10:17 UTC, po3rin commented on articles/po3rin.re
> +ここまでの実装で気付きでしょうが、@<list>{main3}においてgorutineで走らせているすべての関数はcontextでキャンセル可能になっています。これにより特定のシグナルもしくはerrgroupがエラーを検知したらコンテキストキャンセルが行われ、すべてのgorutineで起動しているプロセスをきっちり終了できます(@<img>{cancel})。当然@<code>{SIGTERM}
テンションで書いてしまった。。スレッドも良さそうですが公式に習って「サブタスク」でも良さそうです。
https://godoc.org/golang.org/x/sync/errgroup

2020-02-12 10:25 UTC, po3rin commented on articles/po3rin.re
> +//}
```
method wrap channel
```

で行きます！

2020-02-12 10:30 UTC, po3rin commented
指摘いただいた箇所は修正済みです。議論の余地があるところだけunresolvedにのままにしています。

2020-02-12 10:31 UTC, po3rin commented on articles/po3rin.re
> +	<-ctx.Done()
呼び出し元でキャンセルされることを想定している旨を追加しました

2020-02-12 10:32 UTC, po3rin commented on articles/po3rin.re
> +@<img>{arch}をみて分かるとおりRaftで別のノードと通信する必要があるのでそれらの管理もこのraftalgパッケージの責務です。etcd/raftが本当にRaftアルゴリズムのコアだけに集中して作られたパッケージだということが見て取れます。このraftalgパッケージを使うと先ほどの実装(@<img>{kv})が@<img>{arch2}のように変わります。
こんな感じにこんな感じに修正しました
<img width="651" alt="arch2" src="https://user-images.githubusercontent.com/29445112/74326818-69b08800-4dce-11ea-8027-f7ab1a515576.png">

2020-02-12 10:33 UTC, budougumi0617 commented
生成されたPDFを確認してください。
https://275-223696238-gh.circle-artifacts.com/0/golangtokyo-shoten8.pdf

2020-02-12 14:15 UTC, skanehira reviewed
ちょっとだけ見ました
引き続き見ていきます

2020-02-12 14:15 UTC, skanehira commented on articles/po3rin.re
> +@<b>{コンセンサスアルゴリズム}はクラスターのノードの一部の障害に耐えることを可能にするアルゴリズムです。安全な分散システムを構築する上で重要な役割を果たします。Raftの前にそもそもなぜコンセンサスアルゴリズムが必要なのかを見ていきましょう。たとえばチームで１つのプロセスだけでデータストアを運用している場合、そのデータストアが障害で落ちたら重大な問題になります。その為、高可用性を担保するた
1行よりも、適宜に改行を入れるとレビューしやすいです。
markdownと同じで1行だけ改行してもre:viewは改行にならないので出来上がったPDFは一文になります。

2020-02-12 14:15 UTC, skanehira commented on articles/po3rin.re
> +//}
画像は`{}`なしでも書けますよ

```
//image[gorilla/about_tui_tool][筆者が作ったdockerのTUIツール][scale=0.9]
```

2020-02-12 14:15 UTC, skanehira commented on articles/po3rin.re
> +そこでデータストアなどを@<b>{State machine}としてとらえることが重要になります。State machineを超シンプルに説明すると、「同じ操作を同じ順序で実行すれば必ず同じ状態になる」というモデルです。今回の例でいうと50円入金、30円入金、20円入金と、入力によってデータストアの状態が決定します(@<img>{ha3})。つまりデータストアはState Machineとしてモ
指摘ではないのですが、ジャーナリングファイルシステムと似ていますね

2020-02-12 14:15 UTC, skanehira commented on articles/po3rin.re
> +コンセンサスアルゴリズムにはいくつか種類があり、その中で@<b>{Paxos}というアルゴリズムが過去10年間メインで使われ続けていました。一方でPaxosのアルゴリズムはかなり複雑で理解が難しいものでした。そこで登場したのが@<b>{Raft}@<fn>{raft}というアルゴリズムです。Raftの論文によれば、RaftはPaxosと同じくらい信頼性と効率性がある一方で、PaxosよりRaft
前の節で`@<fn>{raft}`しているので、ここはなくても良いかと思います
```
そこで登場したのが@<b>{Raft}@<fn>{raft}というアルゴリズムです。
```

2020-02-12 14:15 UTC, skanehira commented on articles/po3rin.re
> +Raftの論文においてはリーダーの選出方法が先に説明がありますが、本章では理解しやすさのためにログ複製の管理をどのように行っているかを先に説明します。Raftは最初に1人のリーダーを選出し、複製されたログの管理に関する完全な責任をリーダーに与えることによってコンセンサスを実現します。クライアントからのリクエストは必ずリーダーが受け取ります(@<img>{logrep1})。もしリクエストがフォロ
日本語が変な気がします。
```
Raftの論文においてはリーダーの選出方法が先に説明がありますが、本章では理解しやすさのためにログ複製の管理をどのように行っているかを先に説明します。
```

↓こう？

```
Raftの論文においてはリーダーの選出方法を先に説明していますが、本章では理解しやすさのためにログ複製の管理をどのように行っているかを先に説明します。
```

2020-02-12 14:15 UTC, skanehira commented on articles/po3rin.re
> +Raftの論文においてはリーダーの選出方法が先に説明がありますが、本章では理解しやすさのためにログ複製の管理をどのように行っているかを先に説明します。Raftは最初に1人のリーダーを選出し、複製されたログの管理に関する完全な責任をリーダーに与えることによってコンセンサスを実現します。クライアントからのリクエストは必ずリーダーが受け取ります(@<img>{logrep1})。もしリクエストがフォロ
リーダー、フォロワーの用語の説明があるとわかりやすくて良いかなと思いました

2020-02-13 00:44 UTC, budougumi0617 commented on articles/po3rin.re
> +今までの実装ではクラスターのノードを起動時に固定しなければなりません。たとえば、運用中にノード数を3から5にしたい時は、またクラスターごと再起動しなければいけません。これでは困るので動的にクラスターのノード数を変更できるようにしてあげましょう。ここからのコードの変更は@<code>{https://github.com/po3rin/kvraft/commit/****}に差分が置いてあります。
なるほど、ではこのPRをマージした後、印刷前に修正PR別に作ってもらえれば！

2020-02-13 00:46 UTC, budougumi0617 approved these changes
私の指摘は全部解決したと思うので、LGTM
（リポジトリなどの修正があること、私は多分覚えていられないので、週末にでも追加PRお願いします。

![LGTM](https://stickershop.line-scdn.net/stickershop/v1/sticker/203682170/android/sticker.png)

2020-02-13 00:47 UTC, budougumi0617 commented on articles/po3rin.re
> +今までの実装ではクラスターのノードを起動時に固定しなければなりません。たとえば、運用中にノード数を3から5にしたい時は、またクラスターごと再起動しなければいけません。これでは困るので動的にクラスターのノード数を変更できるようにしてあげましょう。ここからのコードの変更は@<code>{https://github.com/po3rin/kvraft/commit/****}に差分が置いてあります。
> @<code>{https://github.com/po3rin/kvraft/commit/****}に差分が置いてあります

あ、差分はPRにしておいたほうがURL的にわかりやすいかも。（コミットだとハッシュになっちゃいますよね）

2020-02-14 11:27 UTC, po3rin commented on articles/po3rin.re
> +//}
それは知らなかったです！

2020-02-14 12:06 UTC, po3rin commented on articles/po3rin.re
> +Raftの論文においてはリーダーの選出方法が先に説明がありますが、本章では理解しやすさのためにログ複製の管理をどのように行っているかを先に説明します。Raftは最初に1人のリーダーを選出し、複製されたログの管理に関する完全な責任をリーダーに与えることによってコンセンサスを実現します。クライアントからのリクエストは必ずリーダーが受け取ります(@<img>{logrep1})。もしリクエストがフォロ
いただいた文章そのまま使います！ありがとうございます

2020-02-14 12:17 UTC, budougumi0617 commented
生成されたPDFを確認してください。
https://303-223696238-gh.circle-artifacts.com/0/golangtokyo-shoten8.pdf

2020-02-14 12:31 UTC, po3rin commented on articles/po3rin.re
> +@<b>{コンセンサスアルゴリズム}はクラスターのノードの一部の障害に耐えることを可能にするアルゴリズムです。安全な分散システムを構築する上で重要な役割を果たします。Raftの前にそもそもなぜコンセンサスアルゴリズムが必要なのかを見ていきましょう。たとえばチームで１つのプロセスだけでデータストアを運用している場合、そのデータストアが障害で落ちたら重大な問題になります。その為、高可用性を担保するた
そうですね。。修正にかなり時間かかりそうですがやっていきます

2020-02-14 15:02 UTC, budougumi0617 commented on articles/po3rin.re
> +@<b>{コンセンサスアルゴリズム}はクラスターのノードの一部の障害に耐えることを可能にするアルゴリズムです。安全な分散システムを構築する上で重要な役割を果たします。Raftの前にそもそもなぜコンセンサスアルゴリズムが必要なのかを見ていきましょう。たとえばチームで１つのプロセスだけでデータストアを運用している場合、そのデータストアが障害で落ちたら重大な問題になります。その為、高可用性を担保するた
あー、別にこのままでも構わないですよ。PDFになったときに内容は変わらないので。
（まあreファイル状態でのレビューのしやすさはかなり変わりますが、PDFできればそっち見ているので。

2020-02-15 05:22 UTC, po3rin commented on articles/po3rin.re
> +@<b>{コンセンサスアルゴリズム}はクラスターのノードの一部の障害に耐えることを可能にするアルゴリズムです。安全な分散システムを構築する上で重要な役割を果たします。Raftの前にそもそもなぜコンセンサスアルゴリズムが必要なのかを見ていきましょう。たとえばチームで１つのプロセスだけでデータストアを運用している場合、そのデータストアが障害で落ちたら重大な問題になります。その為、高可用性を担保するた
それではPDFでのレビューをお願いします！

2020-02-15 09:45 UTC, budougumi0617 commented
生成されたPDFを確認してください。
https://321-223696238-gh.circle-artifacts.com/0/golangtokyo-shoten8.pdf

2020-02-15 20:49 UTC, po3rin commented
リポジトリを用意しました
github.com/po3rin/kvrsft

2020-02-16 01:26 UTC, budougumi0617 commented
マージします！

2020-02-16 01:26 UTC, merged