Add how to implement tui tool
golangtokyo/shoten8 pull request #8
Opened 2020-02-05 16:37 UTC by skanehira

# PRの概要
- 日本語の表現が変じゃないかどうか
- ソースコードが明らかに間違っていないかどうか

2020-02-05 16:40 UTC, budougumi0617 commented on articles/gorilla.re
> +よくCLI（Command Line Interface）と混合されますが、CLIは名前のとおりコマンドを使って操作するインタフェースです。
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
Line => LINE (prh)

2020-02-05 16:40 UTC, budougumi0617 commented on articles/gorilla.re
> +TUIとはの節で軽く紹介しましたが、改めて紹介します。
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
改めて => あらためて (prh)

2020-02-05 16:40 UTC, budougumi0617 commented on articles/gorilla.re
> +lazygit@<fn>{about_lazygit}はGitのTUIツールです。gitコマンドをTUIツールでラップしてより使いやすくなっています。
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
git => Git (prh)

2020-02-05 16:40 UTC, budougumi0617 commented on articles/gorilla.re
> +lazygit@<fn>{about_lazygit}はGitのTUIツールです。gitコマンドをTUIツールでラップしてより使いやすくなっています。
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
すくな => 少な (prh)

2020-02-06 01:18 UTC, budougumi0617 commented on articles/gorilla.re
> +よくCLI（Command Line Interface）と混合されますが、CLIは名前のとおりコマンドを使って操作するインタフェースです。
企業のLINE扱いになっている。。。ｗ

2020-02-06 15:11 UTC, budougumi0617 commented on articles/gorilla.re
> +たとえばイメージのパネルで@<code>{c}でコンテナの@<img>{gorilla/docui-create-container}のように作成画面が表示され、必要な項目を入力してコンテナを作成できます。
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
一文に二回以上利用されている助詞 "で" がみつかりました。 (ja-technical-writing/no-doubled-joshi)

2020-02-06 15:11 UTC, budougumi0617 commented on articles/gorilla.re
> +lazygit@<fn>{about_lazygit}はGitのTUIツールです。GitコマンドをTUIツールでラップしてより使いやすくなっています。
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
すくな => 少な (prh)

2020-02-06 15:11 UTC, budougumi0617 commented on articles/gorilla.re
> +=== ファイラー
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
ファイラー => ファイラ (prh)

2020-02-06 15:11 UTC, budougumi0617 commented on articles/gorilla.re
> +とてもシンプルなTUIなので、みなさんもぜひ一緒に手を動かしながら読み進めましょう。
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
なので、 => ですので、 (prh)

2020-02-06 15:11 UTC, budougumi0617 commented on articles/gorilla.re
> +1点注意ですが、このライブラリはWindowsでは正しく描画されないので、今回作成するアプリもWindowsでも正常に動作しません。
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
アプリ => アプリケーション (prh)

2020-02-06 23:25 UTC, budougumi0617 commented on articles/gorilla.re
> +3. ファイルのプレビュー画面を作成し中身を表示する
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
文末が"。"で終わっていません。 (ja-technical-writing/ja-no-mixed-period)

2020-02-06 23:25 UTC, budougumi0617 commented on articles/gorilla.re
> +では、Let's Go！
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
Disallow to use "！". (ja-technical-writing/no-exclamation-question-mark)

2020-02-07 03:40 UTC, budougumi0617 commented on articles/gorilla.re
> +==== 2. ファイル一覧を表示する画面を作成
**[RedPen]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
ValidationError[ParagraphNumber], セクション内のパラグラフ数が最大の"10"を超えています at line: 2. ファイル一覧を表示する画面を作成

2020-02-07 03:40 UTC, budougumi0617 commented on articles/gorilla.re
> +==== 3. ファイルのプレビュー画面を作成し中身を表示する
**[RedPen]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
ValidationError[VoidSection], 節の内容が空です。 at line: 3. ファイルのプレビュー画面を作成し中身を表示する

2020-02-07 03:41 UTC, budougumi0617 commented on articles/gorilla.re
> +ファイルを選択して何かを操作するインタフェースはtview.Table@<fn>{about_tview_table}を使います。
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
Table => テーブル (prh)

2020-02-07 06:37 UTC, budougumi0617 commented on articles/gorilla.re
> +==== 2. ファイル一覧を表示する画面を作成
**[RedPen]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
ValidationError[SectionLength], セクション内の文字数が最大の"1,500"を超えています（1,993） at line: 2. ファイル一覧を表示する画面を作成

2020-02-07 06:38 UTC, budougumi0617 commented on articles/gorilla.re
> +@<code>{SetColumns()}は縦に作成するセルの数とセルのサイズを設定します。渡した引数の分だけ縦にセルを作ります。
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
の分だ => のぶんだ (prh)

2020-02-07 06:38 UTC, budougumi0617 commented on articles/gorilla.re
> +そして、第2引数は行、第3引数は列で、どのセルに置くかを設定します。@<code>{FilePanel}は1行1列目のセルに配置するので第2、3引数はともに0です。
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
一つの文で"、"を3つ以上使用しています (ja-technical-writing/max-ten)

2020-02-07 06:38 UTC, budougumi0617 commented on articles/gorilla.re
> +ここまで実装すると動かすことができます。@<img>{gorilla/tui_files_sample}は動かしたときの様子です。
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
の様 => のよう (prh)

2020-02-07 16:59 UTC, skanehira commented on articles/gorilla.re
> +GUIと同様、マウスとキーボードを使用できます。
GUI が何の略かの説明が必要

2020-02-07 16:59 UTC, skanehira commented on articles/gorilla.re
> +たとえば@<code>{ls}などはCLIの一種です。
なども

2020-02-07 16:59 UTC, skanehira commented on articles/gorilla.re
> +しかし、TUIにもデメリットがあります。TUIはキーボードやマウス、画面などを使用するため自動化に向いていません。
もう少し具体的に説明した方が良い
例えば、キーボードの入力待ちの状態になるので、自動化はできないとか。

2020-02-07 16:59 UTC, skanehira commented on articles/gorilla.re
> +対してCLIは自動化にとても向いています。
もう少し具体的に。
標準入出力力しか使っていないから、自動化しやすいとか

2020-02-07 16:59 UTC, skanehira commented on articles/gorilla.re
> +== TUIツール
TUIツールの紹介

2020-02-07 16:59 UTC, skanehira commented on articles/gorilla.re
> +lazygit@<fn>{about_lazygit}はGitのTUIツールです。GitコマンドをTUIツールでラップしてより使いやすくなっています。
TUIでラップ　→ ラップ

2020-02-07 16:59 UTC, skanehira commented on articles/gorilla.re
> +今回のTUIツールはファイルのビューアです。ビューアの仕様の次になります。
仕様は次になります

2020-02-07 16:59 UTC, skanehira commented on articles/gorilla.re
> +@<code>{SelectedFile()}は現在選択しているファイル情報を取得します。@<code>{f.GetSelection()}は現在テーブルの行と列を取得できるのでそれを利用しています。
現在選択しているテーブルの行と列のindexを取得できるので

2020-02-07 16:59 UTC, skanehira commented on articles/gorilla.re
> +@<code>{SetFiles()}は@<code>{Files}で取得したファイル情報を@<code>{FilePanel.files}にセットします。
@<code>{Files()}

2020-02-07 16:59 UTC, skanehira commented on articles/gorilla.re
> +@<code>{NewFilePanel()}でfilesにセットしてもよいですが、役割が異なるので別関数として切り出します。
1行上に移動

2020-02-07 16:59 UTC, skanehira commented on articles/gorilla.re
> +@<code>{tview.Table}の@<code>{SetSelectionChangedFunc()}を使用することで、現在選択している項目のindexを取得できます。
選択している項目が変わるたびに、現在選択しているセルのindexを取得できる

2020-02-07 16:59 UTC, skanehira commented on articles/gorilla.re
> +今回は画面が2つあって、各画面へのフォーカスなどを@<code>{Pages}が行います。
説明が間違っている、気がするので要確認

2020-02-07 16:59 UTC, skanehira commented on articles/gorilla.re
> + 	file := g.FilePanel.SelectedFile()
この数行は全部追加の行

2020-02-07 16:59 UTC, skanehira commented on articles/gorilla.re
> +=== さいごに
最後に

2020-02-07 17:00 UTC, skanehira commented on articles/gorilla.re
> +=== さいごに
実装のサンプルリポジトリのURLを追加

2020-02-08 01:52 UTC, budougumi0617 commented on articles/gorilla.re
> +==== 2. ファイル一覧を表示する画面を作成
**[RedPen]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
ValidationError[SectionLength], セクション内の文字数が最大の"1,500"を超えています（1,996） at line: 2. ファイル一覧を表示する画面を作成

2020-02-08 01:52 UTC, budougumi0617 commented on articles/gorilla.re
> +対してCLIは一般的に標準入出力を使うだけなので、自動化に向いています。
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
なので、 => ですので、 (prh)

2020-02-08 01:52 UTC, budougumi0617 commented on articles/gorilla.re
> +lazygit@<fn>{about_lazygit}はGitのTUIツールです。Gitコマンドをラップしてより使いやすくなっています。
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
すくな => 少な (prh)

2020-02-08 01:52 UTC, budougumi0617 commented on articles/gorilla.re
> +本章で実装したサンプルコードは筆者のリポジトリ@<fn>{sample_ui_repository}に置いてありますので、全体像を掴んでおきたい方はそちらを参考してください。
**[textlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
掴ん => つかん (prh)

2020-02-08 10:53 UTC, budougumi0617 requested changes
ざっくり見ました！

2020-02-08 10:53 UTC, budougumi0617 commented on articles/gorilla.re
> +@<code>{u}でコンテナを起動、@<code>{d}コンテナを削除できます。
```suggestion
@<code>{u}でコンテナを起動、@<code>{d}でコンテナを削除できます。
```

2020-02-08 10:53 UTC, budougumi0617 commented on articles/gorilla.re
> +TUIとはの節で軽く紹介しましたが、あらためて紹介します。
`とはの節で` 
参照タグが抜けている？

2020-02-08 10:53 UTC, budougumi0617 commented on articles/gorilla.re
> +たとえばイメージのパネルでは、@<code>{c}でコンテナの@<img>{gorilla/docui-create-container}のように作成画面が表示され、必要な項目を入力してコンテナを作成できます。
```suggestion
たとえばイメージのパネルでは、@<code>{c}で@<img>{gorilla/docui-create-container}のようにコンテナの作成画面が表示され、必要な項目を入力してコンテナを作成できます。
```

2020-02-08 10:53 UTC, budougumi0617 commented on articles/gorilla.re
> +また、@<code>{f}で入力画面が表示され、キーワードを入力してEnterを押すと@<img>{gorilla/docui-search}のようにイメージの検索結果一覧を見れます。
> 見れます。

表示できます or 表示されます　とかですかね。口語っぽい。

2020-02-08 10:53 UTC, budougumi0617 commented on articles/gorilla.re
> +	f, err := os.Create(name)
テスト用の一時ファイルならば、 `ioutil.Tempfile`のほうがいいのでは？

2020-02-08 10:53 UTC, budougumi0617 commented on articles/gorilla.re
> +	f, err := os.Create(name)
TempDirのしただから別にこれでもよいのか？

2020-02-08 10:53 UTC, budougumi0617 commented on articles/gorilla.re
> +			if _, ok := exceptedFiles[f.Name()]; !ok {
[MUST]
テストがおかしい気がします。
`exceptedFiles` の中にあればいいので、`tmp` がきてもテストパスしますよね、これ。

2020-02-08 10:53 UTC, budougumi0617 commented on articles/gorilla.re
> +			if _, ok := exceptedFiles[f.Name()]; !ok {
[MUST]
あと、`files`の戻り値だけでやっているので、`a.go` しか帰ってこなくても問題なさそう。

2020-02-08 10:53 UTC, budougumi0617 commented on articles/gorilla.re
> +	})
[IMO]
好みの問題かもしれませんが、テーブルテストなど、前処理の共通化がないなら普通に２つのテストケースとして書きますね。
好みの問題とは別に、一個目の`t.Run`が`fatal`評価なので、１個めの`t.Run`が落ちたらこちら実行されないですよね？

2020-02-08 10:53 UTC, budougumi0617 commented on articles/gorilla.re
> +	})
というか、実行順序が直列保証されちゃうから、やっぱりよくない書き方な気がしますね。

2020-02-08 10:53 UTC, budougumi0617 commented on articles/gorilla.re
> +==== 2. ファイル一覧を表示する画面を作成
この辺の静的解析エラーはもう少し節を小分けする、とかで対応ですかね。やっぱり過剰反応かなああ。

2020-02-08 10:53 UTC, budougumi0617 commented on articles/gorilla.re
> +==== 3. ファイルのプレビュー画面を作成し中身を表示する
エラーの中身は別として、自動で節番号が着くはずなので「3.」とかは書かないほうがいいかも

2020-02-08 13:55 UTC, budougumi0617 commented on articles/gorilla.re
> +	})
> 一個目のt.Runがfatal評価なので、１個めのt.Runが落ちたらこちら実行されないですよね？
https://play.golang.org/p/orULzx38QZm

これは嘘でした、`t.Run`で呼んでいるからあまり関係なかった 🙇 🙇

2020-02-09 01:04 UTC, skanehira commented on articles/gorilla.re
> +	f, err := os.Create(name)
TempDir配下にディレクトリを作成するので、これで良いと思います

2020-02-09 01:08 UTC, skanehira commented on articles/gorilla.re
> +			if _, ok := exceptedFiles[f.Name()]; !ok {
テストが間違っていますね…
修正しました

2020-02-09 01:08 UTC, skanehira commented on articles/gorilla.re
> +			if _, ok := exceptedFiles[f.Name()]; !ok {
テスト修正しました

2020-02-09 01:09 UTC, skanehira commented on articles/gorilla.re
> +	})
>というか、実行順序が直列保証されちゃうから、やっぱりよくない書き方な気がしますね。

`t.Run()`を使わないほうが良いってことですか？

2020-02-09 10:55 UTC, hajimehoshi reviewed
PDF が自動生成されるようになる (= 全ての textlist の指摘を直す?) とレビューする側としてはうれしいです。

2020-02-09 10:55 UTC, hajimehoshi commented on articles/gorilla.re
> +1点注意ですが、このライブラリはWindowsでは正しく描画されないです。Windowsの方はWSLなどを使って実装してください。
「Windowsでは」というより、「Windowsのコマンドプロンプトでは」?

2020-02-09 10:55 UTC, hajimehoshi commented on articles/gorilla.re
> +	})
単純に TestFiles を 2 つに分けたほうがいいんじゃないでしょうか?

2020-02-09 11:23 UTC, budougumi0617 commented on articles/gorilla.re
> +	})
はい、星さんと同じ意見で、１つにまとめている意図がよくわかりませんでした。

2020-02-09 23:19 UTC, budougumi0617 commented on articles/gorilla.re
> +==== 2. ファイル一覧を表示する画面を作成
**[RedPen]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
ValidationError[SectionLength], セクション内の文字数が最大の"1,500"を超えています（1,995） at line: 2. ファイル一覧を表示する画面を作成

2020-02-09 23:20 UTC, skanehira commented on articles/gorilla.re
> +	})
`Files()`のテストなので、正常系と異常系を1つのテストにしたほうがよいかなと思っていました…
テストを2つに分けました

2020-02-09 23:26 UTC, skanehira commented on articles/gorilla.re
> +==== 3. ファイルのプレビュー画面を作成し中身を表示する
書かないようにしました

2020-02-09 23:27 UTC, skanehira commented on articles/gorilla.re
> +==== 2. ファイル一覧を表示する画面を作成
できればこの構成のままで行きたいですが、問題ないでしょうか？

2020-02-09 23:31 UTC, skanehira commented on articles/gorilla.re
> +また、@<code>{f}で入力画面が表示され、キーワードを入力してEnterを押すと@<img>{gorilla/docui-search}のようにイメージの検索結果一覧を見れます。
修正しました

2020-02-09 23:31 UTC, skanehira commented on articles/gorilla.re
> +1点注意ですが、このライブラリはWindowsでは正しく描画されないです。Windowsの方はWSLなどを使って実装してください。
修正しました

2020-02-09 23:39 UTC, skanehira commented on articles/gorilla.re
> +TUIとはの節で軽く紹介しましたが、あらためて紹介します。
修正しました

2020-02-09 23:40 UTC, skanehira commented on articles/gorilla.re
> +@<code>{u}でコンテナを起動、@<code>{d}コンテナを削除できます。
ありがとうございます！

2020-02-09 23:42 UTC, budougumi0617 commented on articles/gorilla.re
> +==== ファイル一覧を表示する画面を作成
**[RedPen]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
ValidationError[ParagraphNumber], セクション内のパラグラフ数が最大の"10"を超えています at line: ファイル一覧を表示する画面を作成

2020-02-09 23:42 UTC, budougumi0617 commented on articles/gorilla.re
> +==== ファイル一覧を表示する画面を作成
**[RedPen]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
ValidationError[SectionLength], セクション内の文字数が最大の"1,500"を超えています（1,995） at line: ファイル一覧を表示する画面を作成

2020-02-10 11:30 UTC, po3rin reviewed
お願いします！

2020-02-10 11:30 UTC, po3rin commented on articles/gorilla.re
> +@<code>{u}でコンテナを起動、@<code>{d}コンテナを削除できます。
「docuiというTUIツールですが〜」で始めると次の行で例に出しているコマンドがdocuiの機能と一瞬勘違いしそうです。

2020-02-11 03:51 UTC, budougumi0617 commented
16ページ中10ページが同じ節に入っているので、バランスが悪いですね。直したほうがよさそうです。
<img width="707" alt="スクリーンショット 2020-02-11 12 50 27" src="https://user-images.githubusercontent.com/1883265/74209933-1e628080-4ccd-11ea-93c2-8c80ca7044bc.png">

2020-02-11 03:52 UTC, budougumi0617 commented on articles/gorilla.re
> +==== 2. ファイル一覧を表示する画面を作成
リンク先のとおりなので修正していただきたいです。
https://github.com/golangtokyo/shoten8/pull/8#issuecomment-584468197

2020-02-11 04:06 UTC, budougumi0617 commented on articles/gorilla.re
> +続いて、file_test.goファイルを作成して、@<list>{test_get_files}のテストを書きます。
file_test.go も装飾したほうが良さそうです。全角アンダースコアのように見える。
<img width="172" alt="スクリーンショット 2020-02-11 13 05 07" src="https://user-images.githubusercontent.com/1883265/74210489-52d73c00-4ccf-11ea-9036-6b3f998c93d1.png">

2020-02-11 04:10 UTC, budougumi0617 commented on articles/gorilla.re
> +@<code>{NewFilePanel()}でfilesにセットしてもよいですが、役割が異なるので別関数として切り出します。
`files`も変数名なので装飾したほうが良さそう。indexは用語としてのindexなので、カタカナのほうがよいかも。

2020-02-11 04:11 UTC, budougumi0617 commented on articles/gorilla.re
> +たとえば、@<code>{SetColumns(5, 0)}の場合は、次図のように縦1つ目のセルのサイズは5で、右半分のサイズは残りの領域をすべて使います。
アスキーアート（？）だから参照が貼れないのか！

2020-02-11 04:13 UTC, budougumi0617 commented on articles/gorilla.re
> +//}
PDFにしても右のほうが大きく見えるのですが、「均等サイズ」は「幅」は無視した「高さ」の問題でしょうか？
<img width="337" alt="スクリーンショット 2020-02-11 13 11 21" src="https://user-images.githubusercontent.com/1883265/74210687-05a79a00-4cd0-11ea-822b-581cf2f4acd8.png">

2020-02-11 04:15 UTC, budougumi0617 commented
あ、あと `articles/contributors.re`  に自己紹介の記載をお願いします！

2020-02-12 12:44 UTC, skanehira commented on articles/gorilla.re
> +続いて、file_test.goファイルを作成して、@<list>{test_get_files}のテストを書きます。
修正しました

2020-02-12 12:45 UTC, skanehira commented on articles/gorilla.re
> +@<code>{NewFilePanel()}でfilesにセットしてもよいですが、役割が異なるので別関数として切り出します。
修正しました

2020-02-12 12:46 UTC, skanehira commented on articles/gorilla.re
> +たとえば、@<code>{SetColumns(5, 0)}の場合は、次図のように縦1つ目のセルのサイズは5で、右半分のサイズは残りの領域をすべて使います。
コードにしているので、貼れないですね…

2020-02-12 12:46 UTC, skanehira commented on articles/gorilla.re
> +//}
分かりづらいですね…
えっと、次の流れが正なのでそれに修正しました。

```
たとえば、@<code>{SetColumns(5, 0)}の場合は、次図のように縦1つ目のセルのサイズは5で、右半分のサイズは残りの領域をすべて使います。

//cmd{
+-----+----------+
|     |          |
|     |          |
|     |          |
|     |          |
|     |          |
+-----+----------+
//}

今回は0を2つ渡したので、均等サイズのセルが2つ作られます。
```

2020-02-12 12:59 UTC, skanehira commented on articles/gorilla.re
> +@<code>{u}でコンテナを起動、@<code>{d}コンテナを削除できます。
`これをCLIで行うと次のコマンドを入力して実行する必要があります。`という文がありますが、これも分かりづらいって感じですか？？

2020-02-12 14:02 UTC, budougumi0617 commented
生成されたPDFを確認してください。
https://280-223696238-gh.circle-artifacts.com/0/golangtokyo-shoten8.pdf

2020-02-12 21:59 UTC, budougumi0617 reviewed
こまかいところばかりでごめんなさい、もう少しだけおねがいします 🙏

2020-02-12 21:59 UTC, budougumi0617 commented on articles/contributors.re
> +== @<chap>{gorilla} TUIツールを作ろう / @gorilla0513
👍

2020-02-12 21:59 UTC, budougumi0617 commented on articles/gorilla.re
> +@<code>{u}でコンテナを起動、@<code>{d}コンテナを削除できます。
dコンテナ、になっているので、「d でコンテナ」のほうが良さそう

2020-02-12 21:59 UTC, budougumi0617 commented on articles/gorilla.re
> +=== JSON
他のセクションタイトル的にここは tsonな気がしますね。（Dockerというタイトルでdocuiの紹介にはなっていないけれど、ここはJSONというタイトルでtsonの紹介をしている。）

2020-02-12 21:59 UTC, budougumi0617 commented on articles/gorilla.re
> +=== ファイラ
そうなるとここのタイトルもffかな？

2020-02-12 21:59 UTC, budougumi0617 commented on articles/gorilla.re
> +//}
そしたら「高さが」均等サイズの にしたほうが引っかかりがないかもしれません。（幅と面積は均等じゃないのでちょっとひっかかる）

2020-02-13 02:45 UTC, skanehira commented on articles/gorilla.re
> +@<code>{u}でコンテナを起動、@<code>{d}コンテナを削除できます。
修正しました

2020-02-13 02:46 UTC, skanehira commented on articles/gorilla.re
> +=== JSON
`tson`にしました

2020-02-13 02:46 UTC, skanehira commented on articles/gorilla.re
> +=== ファイラ
`ff`にしました

2020-02-13 02:46 UTC, skanehira commented on articles/gorilla.re
> +今回のTUIツールはファイルのビューアです。ビューアの仕様の次になります。
修正Done

2020-02-13 02:47 UTC, skanehira commented on articles/gorilla.re
> +@<code>{SetFiles()}は@<code>{Files}で取得したファイル情報を@<code>{FilePanel.files}にセットします。
修正Done

2020-02-13 02:48 UTC, skanehira commented on articles/gorilla.re
> +//}
「高さ」ではなく「列の幅」ですね
それを追記しておきました。

2020-02-13 02:54 UTC, budougumi0617 commented
生成されたPDFを確認してください。
https://285-223696238-gh.circle-artifacts.com/0/golangtokyo-shoten8.pdf

2020-02-13 03:12 UTC, budougumi0617 commented on articles/gorilla.re
> +今回は0を2つ渡したので、列の幅が均等サイズのセルが2つ作られます。
幅（width）っていうと、横だと思うんですけど、幅が均等っていうのは図と解説が合ってない気がするのですが…

![スクリーンショット_2020-02-13_12_09_59](https://user-images.githubusercontent.com/1883265/74398152-05d3a100-4e5a-11ea-9ac2-7aba8e824513.png)

2020-02-13 13:22 UTC, skanehira commented on articles/gorilla.re
> +今回は画面が2つあって、各画面へのフォーカスなどを@<code>{Pages}が行います。
合っていた

2020-02-13 14:05 UTC, budougumi0617 commented on articles/gorilla.re
> +今回は0を2つ渡したので、列の幅が均等サイズのセルが2つ作られます。
あーー、なるほど。
そしたら、`@<list>{gui_methods}の例では、SetColumns メソッドの引数はどちらも0を渡したので` とかがいいですかね。「今回」は「あれ」「それ」のような指示詞と一緒なので、何を「今回」といっているのかよくわからないです。

2020-02-13 14:40 UTC, skanehira commented on articles/gorilla.re
> +今回は0を2つ渡したので、列の幅が均等サイズのセルが2つ作られます。
確かに分かりづらいですね。
修正しました

2020-02-13 14:43 UTC, budougumi0617 commented
生成されたPDFを確認してください。
https://295-223696238-gh.circle-artifacts.com/0/golangtokyo-shoten8.pdf

2020-02-13 14:49 UTC, budougumi0617 approved these changes
私はLGTMです。 @po3rin さんがOKならばマージでいいと思います！

![LGTM](https://stickershop.line-scdn.net/stickershop/v1/sticker/203682170/android/sticker.png)

2020-02-16 02:15 UTC, budougumi0617 commented
生成されたPDFを確認してください。
https://351-223696238-gh.circle-artifacts.com/0/golangtokyo-shoten8.pdf

2020-02-16 02:21 UTC, budougumi0617 commented
生成されたPDFを確認してください。
https://361-223696238-gh.circle-artifacts.com/0/golangtokyo-shoten8.pdf

2020-02-16 04:50 UTC, po3rin approved these changes
LGTMです！

2020-02-16 08:53 UTC, budougumi0617 commented
生成されたPDFを確認してください。
https://386-223696238-gh.circle-artifacts.com/0/golangtokyo-shoten8.pdf

2020-02-16 08:54 UTC, merged